### ISSUE TITLE
Make configure option to support system packages rather than submodules

### ISSUE THREAD

**Issue by marxin** [google/bloaty#142]
Hello.

I really like the package but as it is it's not feasible for distribution. Can you please make it using system packages?

**Comment by haberman** [comment]
I'm happy to accept a PR for this. I'm not sure exactly when I would get to it.

I want the tarball to be buildable on its own. But I would like to see CMake options that let you prefer system libs instead.

**Comment by haberman** [comment]
This is fixed by https://github.com/google/bloaty/pull/155

**Comment by marxin** [comment]
Thank you for that. Can you please document how can one use it? I still see submodule cloning during cmake build by default?
